// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.25.0

package sqlc

import (
	"database/sql"
)

type Breve struct {
	ID       int32         `json:"id"`
	Redirect string        `json:"redirect"`
	Link     string        `json:"link"`
	Clicked  sql.NullInt32 `json:"clicked"`
	Random   sql.NullBool  `json:"random"`
	Created  sql.NullTime  `json:"created"`
}
