CREATE TABLE breve(
  id        INT NOT NULL UNIQUE AUTO_INCREMENT PRIMARY KEY,
  redirect  TEXT NOT NULL,
  link      TEXT NOT NULL,
  clicked   INT DEFAULT 0,
  random    BOOLEAN DEFAULT TRUE,
  created   DATE DEFAULT CURRENT_TIMESTAMP
);
