// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.25.0

package database

import (
	"time"
)

type Link struct {
	ID        int32     `json:"id"`
	Redirect  string    `json:"redirect"`
	Url       string    `json:"url"`
	Clicked   int32     `json:"clicked"`
	Random    bool      `json:"random"`
	CreatedAt time.Time `json:"created_at"`
}
