CREATE TABLE IF NOT EXISTS links (
  id          INT  NOT NULL AUTO_INCREMENT PRIMARY KEY,
  redirect    VARCHAR(255) NOT NULL,
  url         VARCHAR(255) NOT NULL UNIQUE,
  clicked     INT NOT NULL DEFAULT 0,
  random      BOOLEAN NOT NULL DEFAULT false,
  created_at  TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);
