// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.25.0

package model

import (
	"database/sql"
)

type Breve struct {
	ID       int32
	Redirect string
	Link     string
	Clicked  sql.NullInt32
	Random   sql.NullBool
	Created  sql.NullTime
}
